C_C_Project_2024/Areas/Admin/Controllers/OrderController.cs
using C_C_Proj_WebStore.DataAccess.Repository.IRepository;
using C_C_Proj_WebStore.Models;
using C_C_Proj_WebStore.Models.ViewModels;
using C_C_Proj_WebStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;
using System.Linq;
using System.Security.Claims;
using Product = C_C_Proj_WebStore.Models.Product;

namespace C_C_Proj_WebStore.Areas.Admin.Controllers
{
	[Area("Admin")]
    [Authorize]
	public class OrderController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public OrderVM OrderVM { get; set; }
        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
		{
			return View();
		}

        public IActionResult Details(int orderId)
        {
            OrderVM = new ()
            {
                OrderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == orderId, includeProperties: "ApplicationUser"),
                OrderDetail = _unitOfWork.OrderDetail.GetAll(o => o.OrderHeaderId == orderId, includeProperties: "Product")
            };
           
            return View(OrderVM);
        }

        [HttpPost]
        public IActionResult OrderNow()
        {
            var orderDetails = _unitOfWork.OrderDetail.GetAll(o => o.OrderHeaderId == OrderVM.OrderHeader.Id);
            Product product = _unitOfWork.Product.Get(u => u.Id == orderDetails.First().ProductId);
            TempData["productId"] = product.Id;
            _unitOfWork.OrderHeader.Remove(OrderVM.OrderHeader);
            _unitOfWork.Save();
            return RedirectToAction("Details", "Home", new { area = "Customer" });
        }

            [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult UpdateOrderDetail()
        {
            var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeaderFromDb.Name = OrderVM.OrderHeader.Name;
            orderHeaderFromDb.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
            orderHeaderFromDb.StreetAddress = OrderVM.OrderHeader.StreetAddress;
            orderHeaderFromDb.City = OrderVM.OrderHeader.City;
            orderHeaderFromDb.Country = OrderVM.OrderHeader.Country;
            orderHeaderFromDb.PostalCode = OrderVM.OrderHeader.PostalCode;
            if(!string.IsNullOrEmpty(OrderVM.OrderHeader.Carrier))
            {
                orderHeaderFromDb.Carrier = OrderVM.OrderHeader.Carrier;
            }
            if(!string.IsNullOrEmpty(OrderVM.OrderHeader.TrackingNumber))
            {
                orderHeaderFromDb.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
            }
            _unitOfWork.OrderHeader.Update(orderHeaderFromDb);
            _unitOfWork.Save();
            TempData["Success"] = "Order Details Updated Successfully";
            return RedirectToAction(nameof(Details), new {orderId = orderHeaderFromDb.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult StartProcessing()
        {
            _unitOfWork.OrderHeader.UpdateStatus(OrderVM.OrderHeader.Id, SD.StatusInProcess);
            _unitOfWork.Save();
            TempData["Success"] = "Order Details Updated Successfully";
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult ShipOrder()
        {
            var orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
            orderHeader.Carrier = OrderVM.OrderHeader.Carrier;
            orderHeader.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
            orderHeader.ShippingDate = DateTime.Now;
            orderHeader.OrderStatus = SD.StatusShipped;
            if(orderHeader.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                orderHeader.PaymentDueDate = DateOnly.FromDateTime(DateTime.Now.AddDays(30));
            }

            _unitOfWork.OrderHeader.Update(orderHeader);
            _unitOfWork.Save();
            TempData["Success"] = "Order Shipped Successfully";
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }

        
        public IActionResult OrderProduct()
        {
            var orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
            var orderDetail = _unitOfWork.OrderDetail.Get(o => o.OrderHeaderId == OrderVM.OrderHeader.Id, includeProperties: "Product");
            orderDetail.Product = _unitOfWork.Product.Get(u => u.Id == orderDetail.ProductId, includeProperties: "Category");
            
           
            return View(orderDetail);
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult UpdateProductStock(OrderDetail orderDetail)
        {
            //var claimsIdentity = (ClaimsIdentity)User.Identity;
            //var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
            var orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == orderDetail.OrderHeaderId);
            ApplicationUser userFromDb = _unitOfWork.ApplicationUser.Get(u => u.Id == orderHeader.ApplicationUserId);
            
           
            OrderVM.OrderHeader = orderHeader;
            OrderVM.OrderDetail = _unitOfWork.OrderDetail.GetAll(o => o.OrderHeaderId == orderHeader.Id, includeProperties: "Product");
            Product productFromDb = _unitOfWork.Product.Get(u => u.Id == OrderVM.OrderDetail.First().Product.Id, includeProperties: "Category");
            productFromDb.StockStatus = SD.AvailableInStock;
            orderHeader.OrderStatus = SD.AvailableInStock;
            productFromDb.StockCount += orderDetail.Count;
            _unitOfWork.Product.Update(productFromDb);
            _unitOfWork.OrderHeader.Update(orderHeader);
            _unitOfWork.Save();
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin + "," + SD.Role_Employee)]
        public IActionResult CancelOrder()
        {
            var orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == OrderVM.OrderHeader.Id);
            if(orderHeader.PaymentStatus == SD.PaymentStatusApproved)
            {
                var options = new RefundCreateOptions
                {
                   // Amount = Convert.ToInt32(orderHeader.OrderTotal * 100),
                    Reason = RefundReasons.RequestedByCustomer,
                    PaymentIntent = orderHeader.PaymentIntentId,
                };
                
                var service = new RefundService();
                Refund refund = service.Create(options);

                _unitOfWork.OrderHeader.UpdateStatus(orderHeader.Id, SD.StatusCancelled, SD.StatusRefunded);
            }
            else
            {
                _unitOfWork.OrderHeader.UpdateStatus(orderHeader.Id, SD.StatusCancelled, SD.StatusCancelled);
            }
            
            _unitOfWork.Save();
            TempData["Success"] = "Order Canceled Successfully";
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }

        [ActionName("Details")]
        [HttpPost]
        public IActionResult Details_PAY_NOW(string stripeToken)
        {
            OrderVM.OrderHeader = _unitOfWork.OrderHeader
                .Get(u => u.Id == OrderVM.OrderHeader.Id, includeProperties: "ApplicationUser");
            OrderVM.OrderDetail = _unitOfWork.OrderDetail
                .GetAll(o => o.OrderHeaderId == OrderVM.OrderHeader.Id, includeProperties: "Product");

            var domain = "https://localhost:7162/";
            var options = new SessionCreateOptions
            {
                SuccessUrl = domain + $"Admin/Order/PaymentConfirmation?orderHeaderId={OrderVM.OrderHeader.Id}",
                CancelUrl = domain + $"Admin/Drder/Details?orderId={OrderVM.OrderHeader.Id}",
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
            };

            foreach (var item in OrderVM.OrderDetail)
            {
                var sessionLineItemOptions = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)item.Price * 100,
                        Currency = "ils",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Product.ShoeModel
                        }
                    },
                    Quantity = item.Count
                };
                options.LineItems.Add(sessionLineItemOptions);
            }
            var service = new SessionService();
            Session session = service.Create(options);
            _unitOfWork.OrderHeader.UpdateStripePaymentId(OrderVM.OrderHeader.Id, session.Id, session.PaymentIntentId);
            _unitOfWork.Save();
            Response.Headers.Add("Location", session.Url);
            return StatusCode(303);
        }

        public IActionResult PaymentConfirmation(int orderHeaderId)
        {
            OrderHeader orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == orderHeaderId, includeProperties: "ApplicationUser");
            if (orderHeader.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                var service = new SessionService();
                Session session = service.Get(orderHeader.SessionId);

                if (session.PaymentStatus.ToLower() == "paid")
                {

C_C_Project_2024/Areas/Admin/Controllers/UserController.cs
using C_C_Proj_WebStore.DataAccess.Data;
using C_C_Proj_WebStore.DataAccess.Repository.IRepository;
using C_C_Proj_WebStore.Models;
using C_C_Proj_WebStore.Models.ViewModels;
using C_C_Proj_WebStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace C_C_Proj_WebStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly IUnitOfWork _unitOfWork;
        public UserController(UserManager<IdentityUser> userManager, IUnitOfWork unitOfWork, RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
            _unitOfWork = unitOfWork;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
           return View();
        }

        public IActionResult RoleManagment(string userId)
        {
            RoleManagmentVM RoleVM = new RoleManagmentVM()
            {
                ApplicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == userId, includeProperties: "Company"),
                RoleList = _roleManager.Roles.Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Name
                }),
                CompanyList = _unitOfWork.Company.GetAll().Select(i => new SelectListItem
                {
                    Text = i.Name,
                    Value = i.Id.ToString()
                })
            };
            RoleVM.ApplicationUser.Role = _userManager.GetRolesAsync(_unitOfWork.ApplicationUser.Get(u=>u.Id == userId)).GetAwaiter().GetResult().FirstOrDefault();
            return View(RoleVM);
        }

        [HttpPost]
        public IActionResult RoleManagment(RoleManagmentVM roleManagmentVM)
        {
            string oldRole = _userManager.GetRolesAsync(_unitOfWork.ApplicationUser.Get(u => u.Id == roleManagmentVM.ApplicationUser.Id)).GetAwaiter().GetResult().FirstOrDefault();

            ApplicationUser applicationUser = _unitOfWork.ApplicationUser.Get(u => u.Id == roleManagmentVM.ApplicationUser.Id);
            if (!(roleManagmentVM.ApplicationUser.Role == oldRole))
            {
                if (roleManagmentVM.ApplicationUser.Role == SD.Role_Company)
                {
                    applicationUser.CompanyId = roleManagmentVM.ApplicationUser.CompanyId;
                }
                if(oldRole == SD.Role_Company)
                {
                    applicationUser.CompanyId = null;
                }
                _unitOfWork.ApplicationUser.Update(applicationUser);
                _unitOfWork.Save();
                _userManager.RemoveFromRoleAsync(applicationUser, oldRole).GetAwaiter().GetResult();
                _userManager.AddToRoleAsync(applicationUser, roleManagmentVM.ApplicationUser.Role).GetAwaiter().GetResult();
            }
            else
            {
                if (oldRole == SD.Role_Company && applicationUser.CompanyId != roleManagmentVM.ApplicationUser.CompanyId)
                {
                    applicationUser.CompanyId = roleManagmentVM.ApplicationUser.CompanyId;
                    _unitOfWork.ApplicationUser.Update(applicationUser);
                    _unitOfWork.Save();
                }
            }
           
            return RedirectToAction("Index");
        }








        #region API CALLS


        [HttpGet]
        public IActionResult GetAll()
        {
            List<ApplicationUser> objUserList = _unitOfWork.ApplicationUser.GetAll( includeProperties: "Company").ToList();
            
            foreach (var user in objUserList)
            {
                user.Role = _userManager.GetRolesAsync(user).GetAwaiter().GetResult().FirstOrDefault();

                if(user.Company == null)
                {
                    user.Company = new() { Name = "" };
                }
            }
            return Json(new { data = objUserList });
        }

        [HttpPost]
        public IActionResult LockUnlock([FromBody]string id)
        {
            var objFromDb = _unitOfWork.ApplicationUser.Get(u => u.Id == id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while Locking/Unlocking" });
            }
            if (objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > System.DateTime.Now)
            {
                //user is currently locked, we will unlock them
                objFromDb.LockoutEnd = DateTime.Now;
            }
            else
            {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            }
            _unitOfWork.ApplicationUser.Update(objFromDb);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Operation successful" });
        }

        #endregion
    }
}

C_C_Project_2024/ViewComponents/ShoppingCartViewComponent.cs
using C_C_Proj_WebStore.DataAccess.Repository.IRepository;
using C_C_Proj_WebStore.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace C_C_Proj_WebStore.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (claim != null)
            {
                if(HttpContext.Session.GetInt32(SD.SessionCart) == null)
                {
                    HttpContext.Session.SetInt32(SD.SessionCart, _unitOfWork.ShoppingCard.GetAll(u => u.ApplicationUserId == claim.Value).Count());
                }

                return View(HttpContext.Session.GetInt32(SD.SessionCart));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

C_C_Project_2024/Views/Shared/_Container.cshtml
@using C_C_Proj_WebStore.Utility
@model IEnumerable<Product>

@{
    var uniqueColors = Model.Select(item => item.Color).Distinct().ToList();
    var uniqueCategories = Model.Select(item => item.Category.Name).Distinct().ToList();
    var uniqueSizes = Model.Select(item => item.Size).Distinct().ToList();
    var uniqueBrands = Model.Select(item => item.Brand).Distinct().ToList();
}





<div class="col-lg-3">
    <div class="sidebar m-2">

            <div class="d-flex m-2">
                    <input class="form-control me-2" id="searchField" type="search" placeholder="Search By Model.." aria-label="Search">
                    <button class="btn btn-outline-success" id="buttonID" name="bbb" type="submit">Search</button>
            </div>
        
        <div>
            <legend class="mt-4">Sort By</legend>
            <label for="searchSort" class="form-label mt-1"></label>
            <select class="form-select" id="searchSort">
                <option selected value="0" aria-label="Relevance" data-label="Relevance">Relevance</option>
                <option value="3" aria-label="New Arrivals" data-label="New Arrivals">New Arrivals</option>
                <option value="4" aria-label="Best Sellers" data-label="Best Sellers">Best Sellers</option>
                <option value="1" aria-label="Price: Low to High" data-label="Price: Low to High">Price: Low to High</option>
                <option value="2" aria-label="Price: High to Low" data-label="Price: High to Low">Price: High to Low</option>
                <option value="5" aria-label="Sales" data-label="Sales">Sales</option>
            </select>
        </div>

        <form id="priceRangeForm">
            <div>
                <legend class="mt-4">Sort By Price Range</legend>
                <label for="minPriceRange" class="form-label">Minimum price: <span id="minPriceLabel"></span></label>
                <input type="range" class="form-range" id="minPriceRange" name="minPrice" min="0" max="500" step="10" oninput="updateMinPriceLabel(this.value)">
            </div>

            <div>
                <label for="maxPriceRange" class="form-label">Maximum price: <span id="maxPriceLabel"></span></label>
                <input type="range" class="form-range" id="maxPriceRange" name="maxPrice" min="0" max="1000" step="10" oninput="updateMaxPriceLabel(this.value)">
            </div>
            <div class="mt-2" style="text-align: center">
                <button type="button" class="btn btn-primary btn-sm text-center" onclick="sendR()">Filter</button>
            </div>
        </form>

        

       
        <div>
            <legend class="mt-4">Sort By Gender</legend>
            <label for="inputGender" class="form-label mt-4"></label>
            <select class="form-select" id="inputGender">
                <option value="">All</option>
                <option value="Male">Men</option>
                <option value="Female">Women</option>
            </select>
        </div>

       

        <div>
            <legend class="mt-4">Sort By Category</legend>
            <label for="inputCategory" class="form-label mt-4"></label>
            <select class="form-select" id="inputCategory">
                <option value="">All</option>
                @foreach (var category in uniqueCategories)
                {
                    <option value="@category">@category</option>
                }
            </select>
        </div>


        
        <div class="form-check">
            <legend class="mt-4">Brands</legend>
            @foreach (var brand in uniqueBrands)
            {

                <label class="form-check-label"><input class=" form-check-input" type="checkbox" name="brand" value="@brand"> @brand</label>
                <br>
            }
        </div>

       

        <div class="form-check">
            <legend class="mt-4">Size:</legend>
            @foreach (var size in uniqueSizes)
            {

                <label class="form-check-label"><input class=" form-check-input" type="checkbox" name="size" value="@size"> @size</label>
                <br>
            }
        </div>

       

        <div class="form-check">
            <legend class="mt-4">Color:</legend>
            @foreach (var color in uniqueColors)
            {

                <label class="form-check-label"><input class=" form-check-input" type="checkbox" name="color" value="@color"> @color</label>
                <br>
            }
        </div>

    </div>
</div>
<div class="col-lg-9">
    <div id="items_root" class="row">
        <partial name="_ProductList" />
    </div>
</div>

C_C_Project_2024/Views/Shared/_Copy.cshtml
@using C_C_Proj_WebStore.Utility
@model IEnumerable<Product>


    @foreach (var item in Model)
    {
    <div class="col-lg-3 col-sm-6 animateWithBounce">
            <div class="row p-2">
                <div class="col-12 p-1">
                    <div class="card border-0 shadow border-top border-5 rounded">
                        @if (item.ProductImages != null && item.ProductImages.Count() > 0)
                        {
                            <img src="@item.ProductImages.FirstOrDefault().ImageUrl" class="card-img-top rounded" />
                        }
                        else
                        {
                            <img src="https://placehold.co/500x600/png" class="card-img-top rounded" />
                        }
                        @*  <img src="@item.ImageUrl" class="card-img-top rounded"/>  *@
                        <div class="card-body pb-0">
                            <div class="pl-1">
                                <p class="card-title h5 text-white text-opacity-75 text-uppercase text-center"> @item.ShoeModel </p>
                                <p class="card-title text-warning text-center">by <b>@item.Brand</b></p>
                                <p class="card-title text-white text-center">Age group : <b>@item.AgeGroup</b></p>
                                @if (item.StockStatus == SD.OutOfStock || item.StockStatus == SD.Ordered)
                                {
                                    <p class="card-title text-danger text-center"><b>Out Of Stock</b></p>
                                }
                                else
                                {
                                    <p class="card-title text-success text-center"><b>Available In Stock</b></p>
                                }
                            </div>
                            <div class="pl-1">
                                <p class="text-white text-opacity-75 text-center mb-0">As low as: <span class="text-decoration-line-through">@item.ListPrice.ToString("c")</span> </p>
                            </div>
                            <div class="pl-1">
                                <p class="text-white text-opacity-75 text-center">As low as: <span>@item.Price100.ToString("c")</span> </p>
                            </div>
                        </div>
                        <div>
                            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary bg-gradient border-0 form-control">
                                Details
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

C_C_Project_2024/Views/Shared/_Layout.cshtml
@using C_C_Proj_WebStore.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - C_C_Proj_WebStore_WebStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/CustomEdit.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/C_C_Proj_WebStore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.0.2/css/dataTables.dataTables.min.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/images/Logo.jpg" style="width:70px ">
                   
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="Customer" asp-controller="Home" asp-action="Index">Gallery</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Content Managment</a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item text-white " asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item text-white " asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item text-white " asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item text-white " asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="dropdown-item text-white " asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
                                    </li>
                                </ul>
                            </li>
                        }    
                            
                        <li class="nav-item  text-end">
                            <a class="nav-link " asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>
                    </ul>

                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-light" data-bs-theme="dark">
        <div class="text-center">
            Made with <i class="bi bi-heart-fill"></i> by Us
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"> </script></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/2.0.2/js/dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.tiny.cloud/1/wxr1njidbdzofkzws1op1ur6d2acyt5z6afnci2aszko4rf6/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

C_C_Project_2024/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"> </script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
        </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"> </script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}